spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_mall?useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456

server:
  port: 8083

# notice: not pagehelper.dialect!
pagehelper:
  helper-dialect: mysql

logging:
  level:
    com.hanxiao.spring_mall.mapper: debug

mybatis:
  type-handlers-package: com.hanxiao.spring_mall.typehandler
